const industries = {
  medical: {
    eyebrow: 'Clinic care',
    headline: 'Clear care plans for everyday health needs.',
    lead: 'A calm, patient-first clinic website with practical information, appointment guidance, and trust-building detail.',
    image: 'assets/medical/hero.png',
    services: ['Consultations', 'Preventive care', 'Diagnostics'],
    proof: ['Experienced care team', 'Clear treatment guidance', 'Easy appointment access'],
    secondary: 'A clinic experience designed around clarity, continuity, and comfort.',
  },
  hospital: {
    eyebrow: 'Hospital care',
    headline: 'Specialist care with a smoother patient journey.',
    lead: 'Present departments, facilities, and appointment paths in a way that feels reassuring before the first visit.',
    image: 'assets/hospital/hero.png',
    services: ['Specialist departments', 'Emergency support', 'Diagnostics'],
    proof: ['Coordinated care', 'Modern facilities', 'Patient support'],
    secondary: 'Help families understand where to go, whom to contact, and what to expect.',
  },
  restaurant: {
    eyebrow: 'Restaurant',
    headline: 'Make guests want to book before they finish scrolling.',
    lead: 'Show the food, the atmosphere, and the practical details people need before choosing where to dine.',
    image: 'assets/restaurant/hero.png',
    services: ['Signature menu', 'Private dining', 'Reservations'],
    proof: ['Seasonal dishes', 'Welcoming ambience', 'Clear hours and location'],
    secondary: 'Food-led visuals and fast booking paths turn curiosity into table reservations.',
  },
  realestate: {
    eyebrow: 'Real estate',
    headline: 'Show properties with the confidence buyers expect.',
    lead: 'Balance featured listings, neighbourhood context, and direct enquiry paths for serious prospects.',
    image: 'assets/realestate/hero.png',
    services: ['Featured listings', 'Buyer guidance', 'Seller support'],
    proof: ['Neighbourhood insight', 'Clear process', 'Direct consultation'],
    secondary: 'Make it easy to compare, shortlist, and contact the right advisor.',
  },
  interior: {
    eyebrow: 'Interior design',
    headline: 'Sell the taste level before the consultation starts.',
    lead: 'Lead with portfolio quality, process clarity, and enough detail for clients to trust the studio.',
    image: 'assets/interior/hero.png',
    services: ['Residential interiors', 'Space planning', 'Turnkey execution'],
    proof: ['Portfolio-led trust', 'Clear process', 'Material guidance'],
    secondary: 'A polished presentation helps clients picture the result before the first meeting.',
  },
  education: {
    eyebrow: 'Education',
    headline: 'Help families understand the school in minutes.',
    lead: 'Organise programs, admissions, campus life, and enquiry routes for parents making a considered decision.',
    image: 'assets/education/hero.png',
    services: ['Programs', 'Admissions', 'Campus life'],
    proof: ['Structured curriculum', 'Student support', 'Parent communication'],
    secondary: 'Clarity and warmth matter when families are choosing where children will learn.',
  },
  professional: {
    eyebrow: 'Professional services',
    headline: 'Present expertise with more substance than slogans.',
    lead: 'Explain what you do, how you work, and why a prospect should start a conversation now.',
    image: 'assets/professional/hero.png',
    services: ['Advisory', 'Implementation', 'Ongoing support'],
    proof: ['Clear process', 'Practical outcomes', 'Responsive team'],
    secondary: 'Strong service businesses win trust through specificity and structure.',
  },
  agency: {
    eyebrow: 'Digital agency',
    headline: 'Show strategy, craft, and outcomes in one confident story.',
    lead: 'Present services, selected work, and a clear next step without leaning on vague buzzwords.',
    image: 'assets/agency/hero.png',
    services: ['Brand strategy', 'Web design', 'Growth campaigns'],
    proof: ['Clear positioning', 'Focused portfolio', 'Structured process'],
    secondary: 'A strong agency site proves taste and competence before the first call.',
  },
  construction: {
    eyebrow: 'Construction',
    headline: 'Make materials and capability easy to trust.',
    lead: 'Organise product ranges, delivery support, and project readiness for contractors and buyers.',
    image: 'assets/construction/hero.png',
    services: ['Building materials', 'Bulk supply', 'Project support'],
    proof: ['Clear catalogues', 'Reliable sourcing', 'Fast quote paths'],
    secondary: 'Practical buyers respond to clarity, stock confidence, and direct contact.',
  },
  ecommerce: {
    eyebrow: 'Ecommerce',
    headline: 'Turn product browsing into confident buying.',
    lead: 'Highlight collections, delivery reassurance, and simple product discovery in a polished storefront.',
    image: 'assets/ecommerce/hero.png',
    services: ['Featured collections', 'Shipping support', 'Customer care'],
    proof: ['Product clarity', 'Simple navigation', 'Checkout confidence'],
    secondary: 'Good ecommerce pages reduce friction long before checkout begins.',
  },
  fashion: {
    eyebrow: 'Fashion',
    headline: 'Let the collection carry the brand.',
    lead: 'Use strong imagery, curated edits, and a smooth path from browsing to enquiry or purchase.',
    image: 'assets/fashion/hero.png',
    services: ['New arrivals', 'Lookbooks', 'Private styling'],
    proof: ['Visual curation', 'Editorial tone', 'Easy browsing'],
    secondary: 'Fashion brands sell through mood, fit, and presentation quality.',
  },
  portfolio: {
    eyebrow: 'Portfolio',
    headline: 'Make the work speak before the bio does.',
    lead: 'Show selected projects, capability, and contact options in a way that feels personal but professional.',
    image: 'assets/portfolio/hero.png',
    services: ['Selected work', 'Capabilities', 'Collaborations'],
    proof: ['Focused case studies', 'Clear role', 'Direct contact'],
    secondary: 'A good portfolio makes it easy to understand the work and hire the person behind it.',
  },
  dairy: {
    eyebrow: 'Dairy',
    headline: 'Build trust around freshness and process.',
    lead: 'Present product ranges, sourcing, and delivery with the clarity local buyers expect.',
    image: 'assets/dairy/hero.png',
    services: ['Fresh milk', 'Value-added products', 'Distribution'],
    proof: ['Clean process', 'Reliable supply', 'Simple ordering'],
    secondary: 'Food businesses win when quality feels visible and dependable.',
  },
  socialservice: {
    eyebrow: 'Social service',
    headline: 'Explain the mission and the next useful action.',
    lead: 'Connect programs, impact areas, and participation paths without inflated claims.',
    image: 'assets/socialservice/hero.png',
    services: ['Programs', 'Volunteer support', 'Donations'],
    proof: ['Mission clarity', 'Transparent actions', 'Community focus'],
    secondary: 'The strongest NGO sites make contribution paths simple and credible.',
  },
  temple: {
    eyebrow: 'Temple',
    headline: 'Help devotees find timings, seva, and guidance quickly.',
    lead: 'Balance reverence with practical information for visitors, donors, and families.',
    image: 'assets/temple/hero.png',
    services: ['Darshan timings', 'Seva options', 'Festival updates'],
    proof: ['Clear schedules', 'Respectful tone', 'Simple donation paths'],
    secondary: 'A devotional site should feel serene, useful, and easy to navigate.',
  },
};

module.exports = { industries };
